### ISSUE TITLE
snapshotList issue on ForEach

### ISSUE THREAD

**Issue by DidarSeyidov** [joreilly/MortyComposeKMM#133]
Type '((Any) throws -> Bool) throws -> Any?' cannot conform to 'RandomAccessCollection'

Only concrete types such as structs, enums and classes can conform to protocols

Required by generic struct 'ForEach' where 'Data' = '((Any) throws -> Bool) throws -> Any?'

**Comment by joreilly** [comment]
Thanks for the report.  I just built/ran iOS client here and seemed to work.  Are there any other factors you know about that might effect issue?  I'm using Xcode 15.4 still here fwiw.

**Comment by DidarSeyidov** [comment]
I use xcode 16 and minimum ios version is 15.6

**Comment by DidarSeyidov** [comment]
how can I solve the issue. I do need pagination implementation on ios side of my kmp project

**Comment by joreilly** [comment]
hmm, I've tried with Xcode 16 and it seems to work

**Comment by joreilly** [comment]
The [Kotlin 2.0.21-RC](https://github.com/JetBrains/kotlin/releases/tag/v2.0.21-RC) release is supposed to have better Xcode 16 support....might be worth trying with that there

**Comment by DidarSeyidov** [comment]
hmm, actually I use 'Kotlin 2.0.0'

**Comment by DidarSeyidov** [comment]
Kotlin version did not solve the issue, after that I casted MutableStateFlow<ItemSnapshotList<T>> to MutableStateFlow<List<T>> where RandomAccessCollection supports, the casting cannot solve it too, After checking type of declared variable in swiftUI (let snapshotList = self.viewModel.booksSnapshotList) I saw it gives ( let snapshotList: [Any] ) in both cases too. How dou you think is the issue can be on that
